### ISSUE TITLE
Where is the CarlaUE4Ubuntu.tar.gz?

### ISSUE THREAD

**Issue by kimna4** [munirjojoverge/Self-Driving-Vehicle-Control-Using-Carla#1]
Thank you for sharing your project.
I hope to use this project but I can't find the CarlaUE4Ubuntu.tar.gz.
Where is the CarlaUE4Ubuntu.tar.gz?

**Comment by munirjojoverge** [comment]
Hi Kimma,
It was two heavy to upload.

**Comment by munirjojoverge** [comment]
I'm not sure how to pass it on

**Comment by kimna4** [comment]
@munirjojoverge  Thank you for quick replying.

**Comment by akshaaaaaaa** [comment]
I can i download it?

**Comment by akshaaaaaaa** [comment]
How can i delete it

**Comment by akshaaaaaaa** [comment]
How can i download it
